version: '3'
services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./couchdb_data:/opt/couchdb/data
      - ./couchdb_etc:/opt/couchdb/etc/local.d
    ports:
      - 0.0.0.0:5984:5984