# This file is manually synced to the prod db

version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.4
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
    environment:
      - DEFAULT_HOST=db.pkm.venerablesystems.com
      - DEFAULT_CLIENT_MAX_BODY_SIZE=5M

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=rafi@rafikhan.io

  couchdb:
    image: couchdb:3
    container_name: couchdb
    environment:
      - VIRTUAL_HOST=db.pkm.venerablesystems.com
      - VIRTUAL_PORT=5984
      - LETSENCRYPT_HOST=db.pkm.venerablesystems.com
    volumes:
      - ./couchdb_data:/opt/couchdb/data
      - ./couchdb_etc:/opt/couchdb/etc/local.d



